ARG AIRFLOW_IMAGE=airflow-with-ol:2.8.4-py311
FROM ${AIRFLOW_IMAGE}

USER airflow
RUN pip install --no-cache-dir --upgrade pip setuptools wheel

COPY docker/requirements.gx_bq_pipeline.txt /tmp/requirements.txt

RUN pip install --no-cache-dir -r /tmp/requirements.txt
