ARG AIRFLOW_IMAGE=apache/airflow:2.8.4-python3.11
FROM ${AIRFLOW_IMAGE}

USER airflow

RUN pip install --no-cache-dir "openlineage-airflow" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.8.4/constraints-3.11.txt"
